name: Deploy Edis E-ticaret

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Placeholder
        run: echo "Deploying edis e-ticaret application..."
